export type * as Bifunctor from './Bifunctor';
export type * as Contravariant from './Contravariant';
export * from './compose';
export * as Either from './Either';
export * as Equality from './Equality';
export * as IO from './IO';
export * as List from './List';
export type * as Monoid from './Monoid';
export * as Option from './Option';
export * as Order from './Order';
export * as Predicate from './Predicate';
export * as Task from './Task';
