compressionLevel: mixed
enableColors: true
enableGlobalCache: false
enableInlineHunks: true
nodeLinker: node-modules

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

supportedArchitectures:
  cpu:
    - current
    - x64
    - ia32
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.6.0.cjs
