npmScopes:
  react-universal:
    npmRegistryServer: https://npm.pkg.github.com
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.3.1.cjs
