const INITIAL_MASK = 0b00000001;

const GROUP_MASK = INITIAL_MASK << 1;
const INTERACTIONS_MASK = INITIAL_MASK << 2;
const GROUP_PARENT_MASK = INITIAL_MASK << 3;
const HOVER_INTERACTION_MASK = INITIAL_MASK << 4;

export {
  GROUP_MASK,
  INTERACTIONS_MASK,
  GROUP_PARENT_MASK,
  INITIAL_MASK,
  HOVER_INTERACTION_MASK,
};
