const INITIAL_MASK = 1;

const GROUP_MASK = 2;
const INTERACTIONS_MASK = 3;
const GROUP_PARENT_MASK = 4;
const HOVER_INTERACTION_MASK = 5;

export {
  GROUP_MASK,
  INTERACTIONS_MASK,
  GROUP_PARENT_MASK,
  INITIAL_MASK,
  HOVER_INTERACTION_MASK,
};
