export const globalKeywords = [
  'inherit',
  'initial',
  'revert',
  'revert-layer',
  'unset',
] as const;

export const directionMap = {
  l: ['-left'],
  r: ['-right'],
  t: ['-top'],
  b: ['-bottom'],
  s: ['-inline-start'],
  e: ['-inline-end'],
  x: ['-left', '-right'],
  y: ['-top', '-bottom'],
  '': [''],
  bs: ['-block-start'],
  be: ['-block-end'],
  is: ['-inline-start'],
  ie: ['-inline-end'],
  block: ['-block-start', '-block-end'],
  inline: ['-inline-start', '-inline-end'],
} satisfies Record<string, string[]>;

export const insetMap: Record<string, string[]> = {
  ...directionMap,
  s: ['-inset-inline-start'],
  start: ['-inset-inline-start'],
  e: ['-inset-inline-end'],
  end: ['-inset-inline-end'],
  bs: ['-inset-block-start'],
  be: ['-inset-block-end'],
  is: ['-inset-inline-start'],
  ie: ['-inset-inline-end'],
  block: ['-inset-block-start', '-inset-block-end'],
  inline: ['-inset-inline-start', '-inset-inline-end'],
};

export const cornerMap = {
  l: ['-top-left', '-bottom-left'],
  r: ['-top-right', '-bottom-right'],
  t: ['-top-left', '-top-right'],
  b: ['-bottom-left', '-bottom-right'],
  tl: ['-top-left'],
  lt: ['-top-left'],
  tr: ['-top-right'],
  rt: ['-top-right'],
  bl: ['-bottom-left'],
  lb: ['-bottom-left'],
  br: ['-bottom-right'],
  rb: ['-bottom-right'],
  '': [''],
  bs: ['-start-start', '-start-end'],
  be: ['-end-start', '-end-end'],
  s: ['-end-start', '-start-start'],
  is: ['-end-start', '-start-start'],
  e: ['-start-end', '-end-end'],
  ie: ['-start-end', '-end-end'],
  ss: ['-start-start'],
  'bs-is': ['-start-start'],
  'is-bs': ['-start-start'],
  se: ['-start-end'],
  'bs-ie': ['-start-end'],
  'ie-bs': ['-start-end'],
  es: ['-end-start'],
  'be-is': ['-end-start'],
  'is-be': ['-end-start'],
  ee: ['-end-end'],
  'be-ie': ['-end-end'],
  'ie-be': ['-end-end'],
} satisfies Record<string, string[]>;
