import type { View } from 'react-native';
import { ForwardedStyledComponent } from '@universal-labs/styled';
declare const Table: ForwardedStyledComponent<View>;
declare const THead: ForwardedStyledComponent<View>;
declare const TFoot: ForwardedStyledComponent<View>;
declare const TH: ForwardedStyledComponent<View>;
declare const TD: ForwardedStyledComponent<View>;
declare const TBody: ForwardedStyledComponent<View>;
declare const TR: ForwardedStyledComponent<View>;
export { Table, THead, TFoot, TH, TD, TBody, TR };
