import { ComponentType } from 'react';
import type { ViewProps } from 'react-native';
export declare const Table: ComponentType<ViewProps>;
export declare const THead: ComponentType<ViewProps>;
export declare const TBody: ComponentType<ViewProps>;
export declare const TFoot: ComponentType<ViewProps>;
export declare const TH: ComponentType<ViewProps>;
export declare const TR: ComponentType<ViewProps>;
export declare const TD: ComponentType<ViewProps>;
export declare const Caption: ComponentType<ViewProps>;
