import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NativeTwin from './_lib/NativeTwin';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>{<NativeTwin>{children}</NativeTwin>}</body>
    </html>
  );
}

export { metadata };
