name: Setup Node
description: Installs node and setup dependencies using yarn.

inputs:
  node-version:
    description: The version of Node.js to install
    required: true
    default: 20.14.0

runs:
  using: composite
  steps:
    - name: Install yarn
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: yarn
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Setup .yarnrc.yml
      run: |
        yarn config set npmAuthToken $NPM_TOKEN -H
        yarn config set npmAlwaysAuth true -H
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Install deps with yarn
      run: yarn --immutable
