import { TailwindPresetTheme } from '../types/theme.types';
import { textAlign, verticalAlign } from './aligns';
import { colors } from './colors';
import { blur, dropShadow } from './filters';
import { flex, flexBasis, flexDirection, flexGrow, flexWrap, justifyContent } from './flex';
import {
  fontFamily,
  fontSize,
  fontWeight,
  letterSpacing,
  lineHeight,
  textIndent,
  textShadow,
  textStrokeWidth,
  fontStyle,
  textTransform,
  wordSpacing,
} from './font';
import { resizeMode } from './image';
import {
  borderRadius,
  boxShadow,
  screens,
  duration,
  easing,
  lineWidth,
  objectFit,
  overflow,
  ringWidth,
  spacing,
  verticalBreakpoints,
} from './mixed';
import { aspectRatio, containers, height, maxHeight, maxWidth, width } from './size';
import { rotate, scale, skew, translate } from './transform';

export const theme = {
  blockSize: height,
  blur,
  borderRadius,
  boxShadow,
  screens,
  colors,
  containers,
  dropShadow,
  duration,
  easing,
  flexBasis,
  flexGrow,
  fontFamily,
  fontSize,
  fontWeight,
  height,
  inlineSize: width,
  letterSpacing,
  verticalAlign,
  aspectRatio,
  textTransform,
  textAlign,
  fontStyle,
  objectFit,
  lineHeight,
  lineWidth,
  maxBlockSize: maxHeight,
  maxHeight,
  translate,
  rotate,
  skew,
  scale,
  flex,
  flexDirection,
  flexWrap,
  justifyContent,
  overflow,
  maxInlineSize: maxWidth,
  maxWidth,
  minBlockSize: maxHeight,
  minHeight: maxHeight,
  minInlineSize: maxWidth,
  minWidth: maxWidth,
  ringWidth,
  spacing,
  textIndent,
  textShadow,
  resizeMode,
  textStrokeWidth,
  verticalBreakpoints,
  width,
  wordSpacing,
} satisfies TailwindPresetTheme;
