export const dimensionWithUnit = {
  height: true,
  left: true,
  margin: true,
  marginBottom: true,
  marginEnd: true,
  marginHorizontal: true,
  marginLeft: true,
  marginRight: true,
  marginStart: true,
  marginTop: true,
  marginVertical: true,
  maxHeight: true,
  maxWidth: true,
  minHeight: true,
  minWidth: true,
  padding: true,
  paddingBottom: true,
  paddingEnd: true,
  paddingHorizontal: true,
  paddingLeft: true,
  paddingRight: true,
  paddingStart: true,
  paddingTop: true,
  paddingVertical: true,
  right: true,
  start: true,
  top: true,
  width: true,
  inset: true,
  insetBlock: true,
  insetBlockEnd: true,
  insetBlockStart: true,
  insetInline: true,
  insetInlineEnd: true,
  insetInlineStart: true,
  marginBlock: true,
  marginBlockEnd: true,
  marginBlockStart: true,
  marginInline: true,
  marginInlineEnd: true,
  marginInlineStart: true,
  paddingBlock: true,
  paddingBlockEnd: true,
  paddingBlockStart: true,
  paddingInline: true,
  paddingInlineEnd: true,
  paddingInlineStart: true,
};

export const layout = {
  ...dimensionWithUnit,
  alignContent: true,
  alignItems: true,
  alignSelf: true,
  aspectRatio: true,
  borderBottomWidth: true,
  borderEndWidth: true,
  borderLeftWidth: true,
  borderRightWidth: true,
  borderStartWidth: true,
  borderTopWidth: true,
  borderWidth: true,
  bottom: true,
  display: true,
  end: true,
  flex: true,
  flexBasis: true,
  flexDirection: true,
  rowGap: true,
  gap: true,
  columnGap: true,
  flexGrow: true,
  flexShrink: true,
  flexWrap: true,
  height: true,
  justifyContent: true,
  left: true,
  margin: true,
  marginBottom: true,
  marginEnd: true,
  marginHorizontal: true,
  marginLeft: true,
  marginRight: true,
  marginStart: true,
  marginTop: true,
  marginVertical: true,
  maxHeight: true,
  maxWidth: true,
  minHeight: true,
  minWidth: true,
  overflow: true,
  padding: true,
  paddingBottom: true,
  paddingEnd: true,
  paddingHorizontal: true,
  paddingLeft: true,
  paddingRight: true,
  paddingStart: true,
  paddingTop: true,
  paddingVertical: true,
  position: true,
  right: true,
  start: true,
  top: true,
  width: true,
  zIndex: true,
  direction: true,
  inset: true,
  insetBlock: true,
  insetBlockEnd: true,
  insetBlockStart: true,
  insetInline: true,
  insetInlineEnd: true,
  insetInlineStart: true,
  marginBlock: true,
  marginBlockEnd: true,
  marginBlockStart: true,
  marginInline: true,
  marginInlineEnd: true,
  marginInlineStart: true,
  paddingBlock: true,
  paddingBlockEnd: true,
  paddingBlockStart: true,
  paddingInline: true,
  paddingInlineEnd: true,
  paddingInlineStart: true,
};

export const iosShadow = {
  shadowColor: true,
  shadowOffset: true,
  shadowOpacity: true,
  shadowRadius: true,
};

export const view = {
  ...layout,
  ...iosShadow,
  transform: true,
  backfaceVisibility: true,
  backgroundColor: true,
  borderBlockColor: true,
  borderBlockEndColor: true,
  borderBlockStartColor: true,
  borderBottomColor: true,
  borderBottomEndRadius: true,
  borderBottomLeftRadius: true,
  borderBottomRightRadius: true,
  borderBottomStartRadius: true,
  borderColor: true,
  borderCurve: true,
  borderEndColor: true,
  borderEndEndRadius: true,
  borderEndStartRadius: true,
  borderLeftColor: true,
  borderRadius: true,
  borderRightColor: true,
  borderStartColor: true,
  borderStartEndRadius: true,
  borderStartStartRadius: true,
  borderStyle: true,
  borderTopColor: true,
  borderTopEndRadius: true,
  borderTopLeftRadius: true,
  borderTopRightRadius: true,
  borderTopStartRadius: true,
  opacity: true,

  // Specials
  elevation: true,
  pointerEvents: true,
  isolation: true,
  cursor: true,
  boxShadow: true,
  filter: true,
};

/**
 * For TEXT
 */

export const text = {
  // ios
  fontVariant: true,
  textDecorationColor: true,
  textDecorationStyle: true,
  writingDirection: true,

  // android
  textAlignVertical: true,
  verticalAlign: true,
  includeFontPadding: true,

  // shared
  color: true,
  fontFamily: true,
  fontSize: true,
  fontStyle: true,
  fontWeight: true,
  letterSpacing: true,
  lineHeight: true,
  textAlign: true,
  textDecorationLine: true,
  textShadowColor: true,
  textShadowOffset: true,
  textShadowRadius: true,
  textTransform: true,
  userSelect: true,
};

export const image = {
  transform: true,
  resizeMode: true,
  backfaceVisibility: true,
  borderBottomLeftRadius: true,
  borderBottomRightRadius: true,
  backgroundColor: true,
  borderColor: true,
  borderRadius: true,
  borderTopLeftRadius: true,
  borderTopRightRadius: true,
  overflow: true,
  overlayColor: true,
  tintColor: true,
  opacity: true,
  objectFit: true,
  cursor: true,
};

export const color = {
  shadowColor: true,
  color: true,
  blurRadius: true,
  backgroundColor: true,
  borderBlockColor: true,
  borderBlockEndColor: true,
  borderBlockStartColor: true,
  borderBottomColor: true,
  borderColor: true,
  borderEndColor: true,
  borderLeftColor: true,
  borderRightColor: true,
  borderStartColor: true,
  borderTopColor: true,
  textShadowColor: true,
  overlayColor: true,
  tintColor: true,
};

export const transformItem = {
  perspective: true,
  rotate: true,
  rotateX: true,
  rotateY: true,
  rotateZ: true,
  scale: true,
  scaleX: true,
  scaleY: true,
  translateX: true,
  translateY: true,
  skewX: true,
  skewY: true,
  matrix: true,
};

export const supportStyleAuto = {
  export: true,
  alignSelf: true,
  pointerEvents: true,
  isolation: true,
  writingDirection: true,
  textAlignVertical: true,
  verticalAlign: true,
  textAlign: true,
  userSelect: true,
};

export const supportStyleNone = {
  display: true,
  pointerEvents: true,
  textTransform: true,
  userSelect: true,
};

export const unitless = {
  aspectRatio: true,
  borderBottomWidth: true,
  borderEndWidth: true,
  borderLeftWidth: true,
  borderRightWidth: true,
  borderStartWidth: true,
  borderTopWidth: true,
  borderWidth: true,
  flex: true,
  rowGap: true,
  gap: true,
  columnGap: true,
  flexGrow: true,
  flexShrink: true,
  zIndex: true,
  shadowRadius: true,
  standardDeviation: true,
  spreadDistance: true,
  elevation: true,
  fontSize: true,
  letterSpacing: true,
  lineHeight: true,
  textShadowRadius: true,
};
