import type { Text } from 'react-native';
import { ForwardedStyledComponent } from '@universal-labs/styled';
declare const Span: ForwardedStyledComponent<typeof Text>;
declare const H1: ForwardedStyledComponent<typeof Text>;
declare const H2: ForwardedStyledComponent<typeof Text>;
declare const H3: ForwardedStyledComponent<typeof Text>;
declare const H4: ForwardedStyledComponent<typeof Text>;
declare const H5: ForwardedStyledComponent<typeof Text>;
declare const H6: ForwardedStyledComponent<typeof Text>;
declare const Strong: ForwardedStyledComponent<typeof Text>;
declare const Code: ForwardedStyledComponent<typeof Text>;
declare const P: ForwardedStyledComponent<typeof Text>;
export { Span, H1, H2, H3, H4, H5, H6, Strong, Code, P };
