name: Health Check
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    
      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmAuthToken $NPM_TOKEN -H
          yarn config set npmAlwaysAuth true -H
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install deps with yarn
        run: yarn --immutable

      - name: Run linter
        run: yarn lint

      - name: Run build
        run: yarn build

      - name: Run tests
        run: yarn test